#theme: jekyll-theme-tactile
title: James B. Wendt
google_analytics: UA-26427374-3
description: James B. Wendt is a software engineer at Google DeepMind currently focusing on improving the capabilities of large generative models related to tool use, coding, and structural data understanding. Prior work at Googleincluded topics related to low-resource information extraction, privacy-safe information extraction, semi-supervised learning, and data management and quality.
