#theme: jekyll-theme-tactile
title: James B. Wendt
google_analytics: UA-26427374-3
description: James B. Wendt is a software engineer in Google Research currently focusing on topics related to privacy-safe information extraction, data manaagement systems, and applied ML. Prior to joining Google, he earned his Ph.D. in Computer Science at UCLA, where he explored methods for hardware security and low power design.
